### ISSUE TITLE
Turning steal-tools into a compiler toolchain

### ISSUE THREAD

**Issue by matthewp** [stealjs/rfcs#16]
Similar to gcc and llvm, steal-tools could be a compiler toolchain for JavaScript projects. Issues such as https://github.com/stealjs/steal/issues/768 make me feel that there is some desire here.

Currently steal-tools is a grab-bag of some optimizations. I think it would be a good idea to take a step back and see how we can architect steal-tools better to serve more general compiler functionality.

**Comment by frank-dspeed** [comment]
@matthewp i think that can be closed as steal got this nice steal-tools graph exports and also this toHtml stuff and that it is able already to get used as a complet build tool missing part i think is a Formart for a Object like the one i am proposing that steal return's that then can be reused so i want to abstract away the filesystem and replace it via a object.
