### ISSUE TITLE
Handle npm module and main right

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/rfcs#19]
most now day libs ship with a main and a module property in npm package.json

i would love to discuss how we handle that as module exports the es version and main exports the js version

i am not sure if steal even aims to be es6 compatible does it?

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal #1436](https://github.com/stealjs/steal/issues/1436) via [**ZenHub**](https://www.zenhub.com/)
