### ISSUE TITLE
Make steal-tools be a better bundler

### ISSUE THREAD

**Issue by matthewp** [stealjs/rfcs#9]
I plan on writing an RFC on this, but I would like steal-tools to be competitive with WebPack and Rollup as a standalone bundler. We have the *watch* mode but that's basically it. steal-tools should be as resilient as the other options and provide equivalent hooks.

**Comment by pYr0x** [comment]
what do you mean with a standalone bundler?
would you like to rewrite steal-tools?

**Comment by matthewp** [comment]
I mean making it useable without any knowledge about Steal at all. Meaning it is a complete replacement for WebPack / Browserify and has all of the features that those provide. Of course it will use Steal under the hood, but the idea is that all of the advantages you have from using a server-side bundler rather than a client-side loader, we should have that in Steal.

Note that I'm not sure if this would even be under steal-tools, it could very well be a different project. I haven't written up the RFC so I have only vaguely thought about this so far 😁
